# Generated by Django 5.0.6 on 2024-08-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_role_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='users',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='upi_id',
        ),
    ]
